name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 1.0.2
homepage: https://github.com/flutterchina/dio
author: wendux <824783146@qq.com>

environment:
  sdk: '>=1.9.0 <3.0.0'

dependencies:
  cookie_jar: ^0.0.6

dev_dependencies:
  test: "^0.12.0"
  coverage: "^0.9.3"
  dart_codecov_generator:
    git:
      url: "https://github.com/wendux/dart-codecov.git"
documentation:

